config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index,new,create,destroy]
      devise_for :users, controllers: {
        sessions: "api/v1/sessions"
      }
      resources :posts, only: %i[index create]
      resources :comments, only: %i[index create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  include Devise::JWT::RevocationStrategies::JTIMatcher

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, 
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  before_create :generate_wall_id

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :experiences, dependent: :destroy

  accepts_nested_attributes_for :educations, allow_destroy: true
  accepts_nested_attributes_for :experiences, allow_destroy: true

  has_one_attached :avatar

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def generate_wall_id
    self.wall_id = User.new_token
  end

  private

  def welcome_send
    WelcomeMailer.welcome_send(self).deliver
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::ApplicationController
    def index
      users = User.page(page).per(PER_PAGE)
      render json: success(
        code: 200,
        serialize: UserSerializer,
        objects: users,
        message: "List successfully",
        skip_meta: false
      ), status: :ok
    end

    def destroy
      user = User.find(params[:id])
      if user.destroy
        render json: { message: "Delete user successfully" }, status: :ok
      else
        render json: { message: "Can't not delete user" }, status: :unprocessable_entity
      end
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user.educations.build if @user.educations.empty?
    @user.experiences.build if @user.experiences.empty?
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
    format.html { redirect_to user_url, notice: "User was successfully destroyed." }
    format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number, :encrypted_password, :intro, experiences_attributes: [:company_name], educations_attributes: [:school_name])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render 'devise/shared/error_messages', resource: @user %>

  <div class="container mt-4">
    <div class="row mb-3">
      <div class="col-md-2">
        <%= form.label :name, class: "form-label" %>
      </div>
      <div class="col-md-10">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-2">
        <%= form.label :email, class: "form-label" %>
      </div>
      <div class="col-md-10">
        <%= form.email_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-2">
        <%= form.label :phone_number, class: "form-label" %>
      </div>
      <div class="col-md-10">
        <%= form.text_field :phone_number, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-end">
        <%= form.submit "Save User", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="d-flex justify-content-center align-items-center vh-100">
  <div id="<%= dom_id(user) %>" class="card mb-3 shadow-sm" style="width: 24rem;">
    <div class="card-header bg-primary text-white">
      <h5 class="card-title mb-0">User Information</h5>
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Name:</strong> <%= user.name %></p>
      <p class="card-text"><strong>Email:</strong> <%= user.email %></p>
      <p class="card-text"><strong>Phone Number:</strong> <%= user.phone_number %></p>
    </div>
    <div class="card-footer text-end">
      <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-sm' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @user, local: true) do |form| %>
        <%= render 'devise/shared/error_messages', resource: @user %>

        <div class="form-group mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :email, class: 'form-label' %>
          <%= form.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :phone_number, class: 'form-label' %>
          <%= form.text_field :phone_number, class: 'form-control' %>
        </div>

        <div class="form-group text-center">
          <%= form.submit 'Save User', class: 'btn btn-primary px-5' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="d-flex justify-content-between align-items-center mb-4">
  <h1>Users</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr id="<%= dom_id(user) %>">
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td>
          <%= link_to "Show", user_path(user), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>
  <%= render "form", user: @user %>
<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <!-- Cover Photo -->
  <div class="cover-photo" style="background-image: url('https://picsum.photos/1200/300'); height: 300px; background-size: cover; background-position: center;">
  </div>
  <%= render 'users/shared/profile', user: @user%>
  <%= render 'users/shared/nav_post'%>

  <!-- Main Content -->
  <div class="row mt-4">
    <div class="col-md-4">
      <%= render 'users/shared/intro',  user: @user %>
      <%= render 'users/shared/photo'%>
    </div>
    <div class="col-md-8">
      <%= render 'users/shared/input_post'%>
      <%= render 'users/shared/card'%>
    </div>
  </div>
</div>

<%= render 'users/shared/modal/post', user: @user %>