config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index,new,create,destroy]
      devise_for :users, controllers: {
        sessions: "api/v1/sessions"
      }
      resources :posts, only: %i[index create]
      resources :comments, only: %i[index create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
module Book
  def self.table_name_prefix
    "book_"
  end
end

app/models/book/order.rb
class Book::Order < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :newest, -> { order(created_at: :desc) }
  scope :by_post, ->(post_id) { where(post_id: post_id).order(created_at: :desc) }
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  validates :company_name, presence: true
end

app/models/jwt_denylist.rb
class JwtDenylist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Denylist

  self.table_name = 'jwt_denylist'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  scope :by_user, ->(user_id) { where(user_id: user_id) }
  scope :by_wall, ->(wall_id) { where(wall_id: wall_id) }
  scope :by_user_or_wall, ->(user_id, wall_id) {
    where(user_id: user_id).or(where(wall_id: wall_id))
  }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  include Devise::JWT::RevocationStrategies::JTIMatcher

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, 
         :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  before_create :generate_wall_id

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :educations, dependent: :destroy
  has_many :experiences, dependent: :destroy

  accepts_nested_attributes_for :educations, allow_destroy: true
  accepts_nested_attributes_for :experiences, allow_destroy: true

  has_one_attached :avatar

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def generate_wall_id
    self.wall_id = User.new_token
  end

  private

  def welcome_send
    WelcomeMailer.welcome_send(self).deliver
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!

  def manage
    @user = User.includes(:posts).find_by(id: params[:user_id])
    @posts = @user.posts if @user.present?
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
  PER_PAGE = 5

  def success(
    code: 200,
    serialize: nil,
    objects: nil,
    message: "",
    token: nil,
    skip_meta: true
  )
    data = serialize.new(objects).serializable_hash[:data]
    data.first[:token] = token if token
    {
      status: code,
      message: message,
      data: data,
      meta: skip_meta ? "" : pagination_meta(objects)
    }
  end

  def unauthorized(message: "")
    {
      code: 401,
      message: message
    }
  end

  def page
    params[:page].nil? ? 1 : params[:page].to_i
  end
  
  private

  def pagination_meta(objects)
    {
      current_page: page,
      total_pages: objects.total_pages,
      total_count: objects.total_count,
      next_page: page == objects.total_pages ? page : page + 1,
      prev_page: page >= 1 ? page - 1 : page,
      is_last_page: page == objects.total_pages
    }
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authenticate!

  def index
    @posts = Post.all

    render template: 'accounts/manage'
  end

  def create
    
  end

  private

  def post_params
    params.permit(:title, :context, :image, :user_id)
  rescue ActionController::ParameterMissing
    {}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user.educations.build if @user.educations.empty?
    @user.experiences.build if @user.experiences.empty?
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
    format.html { redirect_to user_url, notice: "User was successfully destroyed." }
    format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number, :encrypted_password, :intro, experiences_attributes: [:company_name], educations_attributes: [:school_name])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class(key)
    case key
    when 'notice' then 'success'
    when 'alert' then 'danger'
    when 'warning' then 'warning'
    when 'info' then 'info'
    else 'secondary'
    end
  end
end

app/helpers/date_helper.rb
module DateHelper
    extend self
    include ActionView::Helpers::DateHelper

    def formatted_time_in_words(from_time, to_time = Time.now)
        distance_of_time_in_words(from_time, to_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'shared/header' %> 
  <div class="content">
    <%= yield %> 
  </div>
  <%= render 'shared/footer' %> 
</body>
</html>

app/views/layouts/footer/_copy_right.html.erb
 <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

app/views/layouts/footer/_links.html.erb
 <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

app/views/layouts/footer/_media.html.erb
 <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">  
    <%= render 'layouts/footer/media' %>
    <%= render 'layouts/footer/links' %>
    <%= render 'layouts/footer/copy_right' %>
</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
   <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Page List", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Projects</a>
        </li>
      </ul>
      <!-- Left links -->

    <!-- Toggle button -->
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

      <div class="d-flex align-items-center">

        <% if current_user %>
          <%= link_to 'Logout', '#', data: { controller: "logout", action: "click->logout#submit" }, class: "dropdown-item" %>
          <%= link_to 'Account', edit_user_registration_path, class: 'btn btn-outline-warning' %>
        <% else %>
          <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-primary" %>
          <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-secondary" %>
        <% end %>

        <a
          data-mdb-ripple-init
          class="btn btn-dark px-3"
          href="https://github.com/mdbootstrap/mdb-ui-kit"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/shared/_remote_modal.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_label_id %>" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= modal_title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/modal/_post.html.erb
<%= render 'shared/remote_modal', 
modal_id: 'postModal', 
modal_label_id: 'postModalLabel', 
modal_title: 'Post Social' do %>

   <%= form_with(local: true, class: 'mx-1 mx-md-4', data: { controller: "post", action: "post#submit" }) do |f| %>
        <div class="mb-3">
            <label class="form-label" for="user_content">Content</label>
            <textarea autofocus="autofocus" autocomplete="Content" class="form-control" name="post[context]" id="user_content" rows="4" cols="50" , data-post-target="context"></textarea>
        </div>
        <div class="mb-3">
            <label class="form-label" for="user_image">Photo</label>
            <input autocomplete="image" class="form-control" type="file" name="post[image]" id="user_image", data-post-target="image">
            <input class="form-control" type="hidden" name="post[wall_id]" value="<%= user.wall_id %>" id="wall_id" data-post-target="wall_id">
        </div>
        <div class="d-grid gap-2">
            <input type="button" name="commit" value="Post" class="btn btn-primary" data-disable-with="Post" data-action="click->post#submit">
        </div>
    <% end %>
<% end %>